// GENERATED by `pnpm finsweet` — do not edit by hand.
// The Finsweet Attributes this project bundles (none yet). Add one with
// `pnpm finsweet add <name>`, e.g. `pnpm finsweet add list combobox`.
import type { FinsweetModule } from './finsweet';

export const FINSWEET_VERSION = '';

export const registry: Record<string, () => Promise<FinsweetModule>> = {};
