// Choose which Finsweet Attributes the bundle includes.
//   pnpm finsweet list                  available attributes, and which are bundled
//   pnpm finsweet add <name...>         e.g. pnpm finsweet add list combobox
//   pnpm finsweet remove <name...>
//   pnpm finsweet sync                  after updating @finsweet/attributes
// Writes src/modules/finsweet-registry.ts, which src/modules/finsweet.ts
// reads. The first `add` installs @finsweet/attributes at an exact version
// (see install() for the unpublished dependencies it has to drop).
// Webflow then needs no Finsweet <script> tag: remove it if one exists.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registryFile = path.join(root, 'src/modules/finsweet-registry.ts');
const pkgDir = path.join(root, 'node_modules/@finsweet/attributes');
const [cmd = 'list', ...names] = process.argv.slice(2);

// @finsweet/attributes 2.x lists ~30 per-attribute packages as dependencies
// that were never published to npm, so a plain install fails with 404.
// Everything is already in its dist/, so each one is removed with a pnpm
// override ("-") in pnpm-workspace.yaml before installing.
async function install() {
  const res = await fetch('https://registry.npmjs.org/@finsweet%2Fattributes/latest');
  if (!res.ok) throw new Error(`npm registry: ${res.status}`);
  const meta = await res.json();
  const ws = path.join(root, 'pnpm-workspace.yaml');
  let yaml = fs.existsSync(ws) ? fs.readFileSync(ws, 'utf8') : '';
  yaml = yaml.replace(/^ {2}'@finsweet\/attributes-[\w-]+': '-'\n/gm, '');
  const lines = Object.keys(meta.dependencies ?? {}).sort().map((d) => `  '${d}': '-'\n`).join('');
  yaml = /^overrides:\n/m.test(yaml) ? yaml.replace(/^overrides:\n/m, `overrides:\n${lines}`) : `${yaml.trimEnd()}\noverrides:\n${lines}`;
  fs.writeFileSync(ws, yaml.replace(/^\n/, ''));
  execFileSync('pnpm', ['add', '--save-exact', `@finsweet/attributes@${meta.version}`], { cwd: root, stdio: 'inherit' });
}

const enabled = () => [...fs.readFileSync(registryFile, 'utf8').matchAll(/^ {2}(\w+): \(\) => import/gm)].map((m) => m[1]);

function available() {
  if (!fs.existsSync(pkgDir)) return null;
  const loader = fs.readFileSync(path.join(pkgDir, 'attributes.js'), 'utf8');
  const map = Object.fromEntries([...loader.matchAll(/case"(\w+)":return import\("\.\/(dist\/[\w-]+\.js)"\)/g)].map((m) => [m[1], m[2]]));
  if (!Object.keys(map).length) throw new Error('Could not read the attribute list from @finsweet/attributes/attributes.js; the package layout changed.');
  const version = JSON.parse(fs.readFileSync(path.join(pkgDir, 'package.json'), 'utf8')).version;
  return { map, version };
}

function write(list) {
  const pkg = available();
  const unknown = list.filter((n) => !pkg.map[n]);
  if (unknown.length) {
    console.error(`Unknown attribute: ${unknown.join(', ')}. Available: ${Object.keys(pkg.map).join(', ')}`);
    process.exit(1);
  }
  const lines = list.sort().map((n) => `  ${n}: () => import('@finsweet/attributes/${pkg.map[n]}'),`);
  fs.writeFileSync(registryFile, `// GENERATED by \`pnpm finsweet\` — do not edit by hand.
// The Finsweet Attributes this project bundles${list.length ? '' : ' (none yet)'}. Change the list with
// \`pnpm finsweet add <name>\` / \`remove <name>\`; after updating the package, \`pnpm finsweet sync\`.
import type { FinsweetModule } from './finsweet';

export const FINSWEET_VERSION = '${list.length ? pkg.version : ''}';

export const registry: Record<string, () => Promise<FinsweetModule>> = {${lines.length ? `\n${lines.join('\n')}\n` : ''}};
`);
  console.log(list.length ? `Bundled: ${list.join(', ')} (@finsweet/attributes ${pkg.version}). Run pnpm build and commit dist/.` : 'No Finsweet Attributes bundled.');
}

if (cmd === 'list') {
  const pkg = available();
  const on = new Set(enabled());
  if (!pkg) console.log(`@finsweet/attributes is not installed. Bundled: ${[...on].join(', ') || 'none'}.\nAdd one with: pnpm finsweet add <name>`);
  else console.log(`@finsweet/attributes ${pkg.version}\n${Object.keys(pkg.map).map((n) => `  ${on.has(n) ? '●' : '○'} ${n}`).join('\n')}`);
} else if (cmd === 'add') {
  if (!names.length) { console.error('usage: pnpm finsweet add <name...>'); process.exit(1); }
  if (!fs.existsSync(pkgDir)) await install();
  write([...new Set([...enabled(), ...names])]);
} else if (cmd === 'remove') {
  write(enabled().filter((n) => !names.includes(n)));
} else if (cmd === 'sync') {
  if (!fs.existsSync(pkgDir)) { console.error('@finsweet/attributes is not installed.'); process.exit(1); }
  write(enabled());
} else {
  console.error('usage: pnpm finsweet list | add <name...> | remove <name...> | sync');
  process.exit(1);
}
